# Generated by Django 2.2.6 on 2020-03-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='uuid',
        ),
        migrations.AddField(
            model_name='key',
            name='key',
            field=models.CharField(default='', max_length=200, verbose_name='Ключ'),
            preserve_default=False,
        ),
    ]
